name: kuma_apps
description: "Aplikasi yang bertujuan untuk bisa membaca manga"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  carousel_slider: 4.2.1
  google_fonts: 6.1.0
  intl: 0.18.1
  json_path: 0.6.2
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  percent_indicator: 4.2.2
  provider: 6.0.5
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  curved_navigation_bar: ^1.0.3
  go_router: ^14.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo/

